business_divsion           = "Ansible"
environment                = "dev"
resource_group_name        = "rg"
resource_group_location    = "East US"
vnet_name                  = "vnet"
vnet_address_space         = ["10.1.0.0/16"]
ansible_subnet_name        = "ansiblesubnet"
ansible_subnet_address     = ["10.1.1.0/24"]
ansible_linuxvm_size       = "Standard_D2s_v3"
ansible_linuxvm_admin_user = "azureuser"
ansible_password           = "azureuser15"
ansible_computer_name      = "hostname"